### ISSUE TITLE
A helper named 'x-toggle' could not be found

### ISSUE THREAD

**Issue by brandonjmckay** [knownasilya/ember-cli-toggle#33] opened 2015-07-20 21:58 UTC
I can't use the component as it seems to make the page fail with `A helper named 'x-toggle' could not be found`. 

I can add a stack trace if needed. I ran `rm -rf node_modules bower_components`, then re-ran `npm install && bower install`.

I'm on Ember 1.13.5, EmberData 1.13.5.

**Comment by knownasilya** [comment] 2015-07-20 23:38
What version of Ember-CLI?

**Comment by knownasilya** [comment] 2015-07-21 00:57
Give the latest version a try please. Thanks.

**Comment by awwester** [comment] 2015-07-21 15:19
@brandonjmckay I'm on 1.13.5/1.13.5 of ember and ember-data and worked for me seamlessly on ember-cli 1.13.1

**Comment by knownasilya** [comment] 2015-07-21 15:41
@awwester you tried the latest version or the one before that?

**Comment by brandonjmckay** [comment] 2015-07-21 16:59
I'll double check which version of cli it is.

**Comment by awwester** [comment] 2015-07-21 20:34
@knownasilya Nope, I have only just picked up this package today and have only used this version set

**Comment by knownasilya** [comment] 2015-07-21 23:51
I just released a new version, give that a try.

**Comment by brandonjmckay** [comment] 2015-07-23 18:46
Will do.

**Comment by gte451f** [comment] 2015-07-28 21:28
Hi Ilya, 
I'm running into the same problem.  I thought perhaps updating the package version & rebuilding my project would help:
package.json....
```
    "ember-cli-toggle": "0.5.11",
 ```

followed by....
```
    rm -rf node_modules bower_components dist tmp
    npm cache clean
    bower cache clean
    npm install
    bower install
```
Didn't seem to make a difference.

**Comment by dgavey** [comment] 2015-07-28 21:57
Us as well.  We are on Ember CLI 0.2.7 and have been using version 0.5.6 up to 0.5.8 however 0.5.9 and up gives us the same error as above.

**Comment by knownasilya** [comment] 2015-07-28 23:11
0.5.9-0.5.10 were bad releases. Does 0.5.11 work for anyone?

**Comment by sir-dunxalot** [comment] 2015-07-29 00:10
I just upgraded to `0.5.11` and an seeing the same issue. Ember `1.13.5`.

**Comment by gte451f** [comment] 2015-07-29 12:23
0.5.11 exhibits this error on my apps using the latest ember CLI release

**Comment by knownasilya** [comment] 2015-07-29 13:57
Ok, I just did the following:

```bash
ember new hello
ember install ember-cli-toggle
ember g controller application
# add `{{x-toggle toggle='startCar'}}` to templates/application.hbs
# add `startCar1 action to controllers/application.js
npm start
```

And everything worked fine. I'm using ember-cli `1.13.1`

**Comment by knownasilya** [comment] 2015-07-29 13:58
Can someone create a repo that reproduces this issue? That would help immensely.

**Comment by gte451f** [comment] 2015-08-05 23:25
I've confirmed that a fresh install works as @knownasilya previously mentioned.
Will try again w/ my local apps and link to a broken example if I'm still not able to get it working.

**Comment by gte451f** [comment] 2015-08-06 00:23
Here is a link to an Ember CLI app that does not work.
[https://github.com/gte451f/smores-mgr] (https://github.com/gte451f/smores-mgr)

There are a couple of  caveats...
1. It normally requires a backing API, just go to the test route and you should avoid API calls  [http://localhost:4200/test] (http://localhost:4200/test)
2. There is a wrinkle in the install mentioned in the readme

**Comment by knownasilya** [comment] 2015-08-12 13:06
@rwjblue @stefanpenner any ideas what the issue might be here? I'm at a loss.

**Comment by brandonjmckay** [comment] 2015-09-24 17:58
Just tried again on a new app, and getting this still.

**Comment by knownasilya** [comment] 2015-09-24 18:37
What is it that you guys are doing that's causing this? I'm going to try to setup a test repo with the working version.

**Comment by brandonjmckay** [comment] 2015-09-24 20:31
If I explicitly import this in my app, and re-export it it works fine.

**Comment by brandonjmckay** [comment] 2015-09-24 20:31
Must be something to do with how it is exporting it into the app.

**Comment by knownasilya** [comment] 2015-09-25 00:48
Maybe something to do with the version of Ember CLI?

**Comment by begemotx2** [comment] 2015-09-25 19:12
Same for me. Ember CLI version 1.13.1
Not sure, if it help, but checked built assets/<app-name>.js file.

Other installed components usually has name '<app-name>/components/<component-name>' such as
```javascript
define('<app-name>/components/x-select', ...
```
but x-toggle is defined as 
```javascript
define('client-app/components/x-toggle/component', ...
```

**Comment by knownasilya** [comment] 2015-09-26 01:29
Sounds like certain versions of ember-cli don't support the syntax where the template is in the addon directory. @rwjblue could that be an issue with some versions of the CLI?

**Comment by knownasilya** [comment] 2016-01-12 12:19
@stefanpenner any thoughts on this issue?

**Comment by stefanpenner** [comment] 2016-01-12 16:46
@knownasilya i need a reproduction to investigate,

the above provided one seems to be hitting some `less` issue, running out of memory.
```
<--- Last few GCs --->

   91802 ms: Scavenge 1395.6 (1457.6) -> 1395.6 (1457.6) MB, 89.1 / 0 ms (+ 2.9 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   93491 ms: Mark-sweep 1395.6 (1457.6) -> 1395.6 (1457.6) MB, 1689.6 / 0 ms (+ 3.9 ms in 2 steps since start of marking, biggest step 2.9 ms) [last resort gc].
   95210 ms: Mark-sweep 1395.6 (1457.6) -> 1395.1 (1457.6) MB, 1718.4 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2ae856ee3ac1 <JS Object>
    1: eval [/Users/stefanpenner/tmp/smores-mgr/node_modules/less/lib/less/tree/ruleset.js:~31] [pc=0x1be21874005b] (this=0x160681d653a9 <JS Object>,context=0x1acf5a8c7419 <JS Object>)
    2: eval [/Users/stefanpenner/tmp/smores-mgr/node_modules/less/lib/less/tree/ruleset.js:~31] [pc=0x1be217cf0242] (this=0x1acf5a8c7631 <JS Object>,context=0x1acf5a8c7419 <JS Object>)
    3: evalCall [/Users/ste...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
fish: 'ember s' terminated by signal SIGABRT (Abort)
```

**Comment by stefanpenner** [comment] 2016-01-12 16:46
^^ doesn't seem to describe the issue here, so I believe it to be orthogonal and maybe something with less? Anyways, if someone provides a reproduction (that works), i'll dig in.

**Comment by knownasilya** [comment] 2016-02-09 14:22
Closing this until someone can produce a clean reproduction.

**Comment by ashishtajane** [comment] 2016-02-18 22:46
I ran into this problem just now. Then I created a fresh repo with just this addon installed and it was still not working.
Repo link - https://github.com/ashishtajane/ember-toggle

After that, I shuffled the addon files a bit and was able to make it work. So I have added those files also in above repo (in `node_modules/ember-cli-toggle` folder)

Here is how the final addon folder looks (in working condition)..
![ember-toggle](https://cloud.githubusercontent.com/assets/1175870/13160715/2fdb7962-d6bf-11e5-8c76-24dbf8132192.png)

**Comment by knownasilya** [comment] 2016-02-19 02:08
Are you by any chance using podModulePrefix?

**Comment by ashishtajane** [comment] 2016-02-19 02:50
I literally just did this

    ember new ember-toggle
    cd ember-toggle
    ember install ember-cli-toggle
    # add to application.hbs following line
    # {{x-toggle value=someValue}}

ember-cli version is `2.3.0-beta.1`
addon version is `0.6.0`

**Comment by knownasilya** [comment] 2016-02-19 23:06
Can you give v0.6.1 a try?

**Comment by ashishtajane** [comment] 2016-02-19 23:43
Works!
Thanks :+1: 

Although there seems to be another issue with CSS. The theme files are not getting imported correctly I think. Because only `default` theme was visible for me. Then I manually copied css of a theme (`ios`) to my `app.css` and that theme became visible. Same with rest of them.

**Closed** 2016-02-20 02:46 UTC
Labels: bug, help wanted

**Comment by knownasilya** [comment] 2016-02-20 02:48
See if #38 helps
